import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,Check,CheckCheck,ChevronRight,Download,Home,Leaf,NotebookPen,Plus,Search,Settings,Sun,Trash2,X} from 'lucide-react';
import {type State,type Routine,type Note,type Book,emptyState,today,period,due,validState} from './model';
import './style.css';
const uid=()=>crypto.randomUUID();
const labels={daily:'日課',weekly:'週課',monthly:'月課',unknown:'未設定',unread:'未読',reading:'読書中',read:'読了'};
function App(){
 const [data,setData]=useState<State>(emptyState()),[page,setPage]=useState('home'),[query,setQuery]=useState(''),[ready,setReady]=useState(false),[save,setSave]=useState('読み込み中'),[error,setError]=useState(''),[date,setDate]=useState(today()),[modal,setModal]=useState<'routine'|'note'|'book'|null>(null),[editing,setEditing]=useState(''),[filter,setFilter]=useState('all'),[category,setCategory]=useState('all'),[dark,setDark]=useState(localStorage.getItem('benrin-theme')==='dark');
 const revision=useRef(0),latest=useRef(data),persisted=useRef(data),saving=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),[routine,setRoutine]=useState<Routine>({id:'',title:'',frequency:'daily',weekdays:[],day:0,paused:false,created:today()}),[note,setNote]=useState<Note>({id:'',title:'',body:'',tags:'',bookId:'',updated:''}),[book,setBook]=useState<Book>({id:'',title:'',author:'',status:'unread',finished:'',rating:0,review:''});
 useEffect(()=>{fetch('/api/state').then(async r=>{if(!r.ok)throw Error('データを読み込めません。ログイン・サーバー設定を確認してください。');return r.json();}).then(v=>{if(!validState(v.state))throw Error('保存データの形式を確認できません。');revision.current=v.revision;latest.current=persisted.current=v.state;setData(v.state);setReady(true);setSave('保存済み');}).catch(e=>setError(e.message));const i=setInterval(()=>setDate(today()),30000);return()=>clearInterval(i);},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('benrin-theme',dark?'dark':'light');},[dark]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(latest.current!==persisted.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[]);
 async function flush(){if(saving.current||latest.current===persisted.current)return;saving.current=true;setSave('保存中…');const snapshot=latest.current;try{const r=await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:snapshot,revision:revision.current})});if(r.status===409)throw Error('別の画面で更新されています。設定から未保存データを書き出してから、再読み込みしてください。');if(!r.ok)throw Error('保存できませんでした。接続を確認して「再試行」を押してください。');revision.current=(await r.json()).revision;persisted.current=snapshot;setError('');setSave('保存済み');}catch(e){setError((e as Error).message);setSave('未保存');saving.current=false;return;}saving.current=false;if(latest.current!==persisted.current)void flush();}
 function update(fn:(s:State)=>State){const next=fn(latest.current);latest.current=next;setData(next);setSave('未保存');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),550);}
 function navigate(p:string){setPage(p);setQuery('');setFilter('all');setCategory('all');}
 function open(kind:'routine'|'note'|'book',id=''){setEditing(id);if(kind==='routine')setRoutine(data.routines.find(x=>x.id===id)||{id:uid(),title:'',frequency:'daily',weekdays:[],day:0,paused:false,created:date});if(kind==='note')setNote(data.notes.find(x=>x.id===id)||{id:uid(),title:'',body:'',tags:'',bookId:'',updated:new Date().toISOString()});if(kind==='book')setBook(data.books.find(x=>x.id===id)||{id:uid(),title:'',author:'',status:'unread',finished:'',rating:0,review:''});setModal(kind);}
 function storeItem(kind:'routine'|'note'|'book',value:Routine|Note|Book){update(s=>{if(kind==='routine')return {...s,routines:[...s.routines.filter(x=>x.id!==value.id),value as Routine]};if(kind==='note')return {...s,notes:[...s.notes.filter(x=>x.id!==value.id),{...value,updated:new Date().toISOString()} as Note]};return {...s,books:[...s.books.filter(x=>x.id!==value.id),value as Book]};});}
 function remove(kind:'routine'|'note'|'book',id:string){if(!confirm('削除しますか？ この操作は取り消せません。日課の実行履歴は残ります。'))return;update(s=>kind==='routine'?{...s,routines:s.routines.filter(x=>x.id!==id)}:kind==='note'?{...s,notes:s.notes.filter(x=>x.id!==id)}:{...s,books:s.books.filter(x=>x.id!==id),notes:s.notes.map(n=>n.bookId===id?{...n,bookId:''}:n)});setModal(null);}
 function mark(r:Routine,status:'done'|'skipped'){const p=period(r,date);update(s=>{const old=s.entries.find(e=>e.routineId===r.id&&e.period===p);return {...s,entries:[...s.entries.filter(e=>!(e.routineId===r.id&&e.period===p)),...(old?.status===status?[]:[{routineId:r.id,period:p,status,at:new Date().toISOString(),title:r.title}])]};});}
 const active=data.routines.filter(r=>due(r,date));const done=active.filter(r=>data.entries.some(e=>e.routineId===r.id&&e.period===period(r,date)&&e.status==='done')).length;
 const matches=(...v:string[])=>v.join(' ').toLowerCase().includes(query.toLowerCase());
 const nav=[['home','ホーム',Home],['routines','日課・週課・月課',CheckCheck],['notes','メモ',NotebookPen],['books','本棚',BookOpen],['settings','設定',Settings]] as const;
 function routineRow(r:Routine){const entry=data.entries.find(e=>e.routineId===r.id&&e.period===period(r,date));return <div className={'routine-row '+(entry?'completed':'')} key={r.id}><button className={'check '+(entry?.status==='done'?'checked':'')} disabled={r.paused||!due(r,date)} aria-label={r.title+'を'+(entry?.status==='done'?'未完了に戻す':'完了にする')} onClick={()=>mark(r,'done')}>{entry?.status==='done'&&<Check size={17}/>}</button><button className="row-title" onClick={()=>open('routine',r.id)}>{r.title}<small>{r.paused?'一時停止中':entry?.status==='skipped'?'今回はスキップ':r.frequency==='monthly'?(r.day?`毎月${r.day}日から`:'月内に1回'):r.frequency==='daily'&&r.weekdays.length?r.weekdays.map(d=>'日月火水木金土'[d]).join('・')+'曜日':labels[r.frequency]}</small></button><span className={'badge '+r.frequency}>{labels[r.frequency]}</span><button className="quiet skip" disabled={r.paused||!due(r,date)} onClick={()=>mark(r,'skipped')}>{entry?.status==='skipped'?'戻す':'スキップ'}</button></div>;}
 function noteCard(n:Note){return <button className="note-card" key={n.id} onClick={()=>open('note',n.id)}><small>{new Date(n.updated).toLocaleDateString('ja-JP',{timeZone:'Asia/Tokyo'})}</small><h3>{n.title||'無題のメモ'}</h3><p>{n.body||'まだ本文がありません'}</p><div className="tags">{n.tags.split(',').filter(Boolean).map((t,i)=><span key={i}>#{t.trim()}</span>)}</div></button>;}
 function bookCard(b:Book){return <button className="book-card" key={b.id} onClick={()=>open('book',b.id)}><div className={'cover '+b.status}><BookOpen size={25}/><strong>{b.title}</strong><small>{b.author||'著者未登録'}</small></div><div><span className="badge">{b.category ? b.category+' · ' : ''}{labels[b.status]}</span><h3>{b.title}</h3><p>{b.author||'著者未登録'}</p>{b.totalVolumes&&<p>{b.readVolumes||'—'} / {b.totalVolumes}巻 {b.sourceStatus==='完結'?'・完結':''}</p>}{b.rating>0&&<span className="stars">{'★'.repeat(b.rating)}</span>}</div></button>;}
 function blank(text:string,kind:'routine'|'note'|'book'){return <div className="empty"><Leaf size={28}/><h3>{text}</h3><p>ひとつずつ、あなたのペースで。</p><button className="primary" onClick={()=>open(kind)}><Plus size={16}/>最初の{kind==='routine'?'日課':kind==='note'?'メモ':'本'}を追加</button></div>;}
 function backup(){const blob=new Blob([JSON.stringify({format:'benrin-v1',exported:new Date().toISOString(),state:latest.current},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`benrin-${date}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 return <div className="app"><aside><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('home')}}><span><Leaf size={24}/></span>benrin<span className="brand-dot">.</span></a><p className="tagline">暮らしの、小さな道具箱。</p><div className="nav-label">MY WORKSPACE</div><nav>{nav.map(([key,label,Icon])=><button className={page===key?'selected':''} key={key} onClick={()=>navigate(key)}><Icon size={19}/>{label}{page===key&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-foot"><span className="status-dot"/>{save}<small>自分だけのスペース</small></div></aside><main><header><span>マイワークスペース <ChevronRight size={13}/> {nav.find(n=>n[0]===page)?.[1]}</span><button className="icon-button" aria-label="表示テーマを切り替え" onClick={()=>setDark(!dark)}><Sun size={20}/></button></header>{error&&<div role="alert" className="error">{error}<button onClick={()=>void flush()}>再試行</button><button onClick={backup}>未保存データを書き出す</button></div>}{!ready?<div className="empty">{error?'読み込みを完了できませんでした。':'道具箱を開いています…'}</div>:<div className="content">
 {page==='home'?<><div className="greeting"><div><p className="eyebrow">{new Date(date+'T00:00:00+09:00').toLocaleDateString('ja-JP',{timeZone:'Asia/Tokyo',month:'long',day:'numeric',weekday:'long'})}</p><h1>今日も、ひとつずつ。</h1><p>やること、思いついたこと、心に残った一冊。</p></div><div className="greeting-art"><Leaf size={64} strokeWidth={1}/><span>MAKE ROOM<br/>FOR YOUR EVERYDAY.</span></div></div><div className="stats"><button onClick={()=>navigate('routines')}><span className="stat-icon green"><CheckCheck/></span><div><small>今日・今週・今月の達成</small><strong>{done}<em> / {active.length}</em></strong></div><div className="progress"><i style={{width:`${active.length?done/active.length*100:0}%`}}/></div></button><button onClick={()=>navigate('notes')}><span className="stat-icon orange"><NotebookPen/></span><div><small>書きとめたメモ</small><strong>{data.notes.length}<em> 件</em></strong></div></button><button onClick={()=>navigate('books')}><span className="stat-icon blue"><BookOpen/></span><div><small>今年読み終えた本</small><strong>{data.books.filter(b=>b.status==='read'&&b.finished.startsWith(date.slice(0,4))).length}<em> 冊</em></strong></div></button></div><section><div className="section-head"><h2>今日のチェックリスト <span>{active.length-done}</span></h2><button className="quiet" onClick={()=>navigate('routines')}>すべて見る <ChevronRight size={15}/></button></div><div className="panel">{active.length?active.map(routineRow):blank('今日は、ここから始めよう','routine')}</div></section><div className="home-columns"><section><div className="section-head"><h2>最近のメモ</h2><button className="quiet" onClick={()=>open('note')}><Plus size={16}/>追加</button></div><div className="note-grid">{data.notes.length?[...data.notes].sort((a,b)=>b.updated.localeCompare(a.updated)).slice(0,2).map(noteCard):blank('思いつきを、忘れないうちに','note')}</div></section><section><div className="section-head"><h2>読書中の本</h2><button className="quiet" onClick={()=>navigate('books')}>本棚へ <ChevronRight size={15}/></button></div>{data.books.some(b=>b.status==='reading')?data.books.filter(b=>b.status==='reading').slice(0,2).map(bookCard):blank('次の一冊を、本棚に','book')}</section></div></>:
 <><div className="page-heading"><div><p className="eyebrow">YOUR LITTLE TOOLBOX</p><h1>{nav.find(n=>n[0]===page)?.[1]}</h1><p>{page==='routines'?'小さな積み重ねを、自分のリズムで。':page==='notes'?'考えやひらめきを、気軽に書きとめる。':page==='books'?'読んだ時間と、心に残った言葉を。':'データと使い心地を整える。'}</p></div>{page!=='settings'&&<button className="primary" onClick={()=>open(page==='routines'?'routine':page==='notes'?'note':'book')}><Plus size={17}/>追加する</button>}</div>
 {page!=='settings'&&<div className="toolbar"><label className="search"><Search size={17}/><input aria-label="検索" placeholder="検索する…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{page==='routines'&&<select aria-label="日課の絞り込み" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">すべて</option><option value="daily">日課</option><option value="weekly">週課</option><option value="monthly">月課</option><option value="history">実行履歴</option></select>}{page==='books'&&<select aria-label="種類の絞り込み" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">すべての種類</option><option value="漫画">漫画</option><option value="小説">小説</option></select>}{page==='books'&&<select aria-label="読書状態の絞り込み" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">すべての本</option>{(['unknown','unread','reading','read'] as const).map(v=><option key={v} value={v}>{labels[v]}</option>)}</select>}</div>}
 {page==='routines'&&(filter==='history'?<div className="panel">{[...data.entries].sort((a,b)=>b.at.localeCompare(a.at)).filter(e=>matches(e.title)).map((e,i)=><div className="history" key={i}><span>{e.status==='done'?'✓ 完了':'− スキップ'}</span><strong>{e.title}</strong><small>{e.period} · {new Date(e.at).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}</small></div>)}{!data.entries.length&&<p className="empty">実行履歴はまだありません。</p>}</div>:<div className="panel">{data.routines.filter(r=>(filter==='all'||r.frequency===filter)&&matches(r.title)).map(routineRow)}{!data.routines.length?blank('続けたいことを、ひとつ','routine'):!data.routines.some(r=>(filter==='all'||r.frequency===filter)&&matches(r.title))&&<p className="empty">該当する日課がありません。</p>}</div>)}
 {page==='notes'&&<div className="note-grid full">{[...data.notes].sort((a,b)=>b.updated.localeCompare(a.updated)).filter(n=>matches(n.title,n.body,n.tags)).map(noteCard)}{!data.notes.length?blank('最初のメモを書いてみよう','note'):!data.notes.some(n=>matches(n.title,n.body,n.tags))&&<p>該当するメモがありません。</p>}</div>}
 {page==='books'&&<div className="books-grid">{data.books.filter(b=>(filter==='all'||filter===b.status)&&(category==='all'||category===b.category)&&matches(b.title,b.author,b.review,b.genre||'')).map(bookCard)}{!data.books.length?blank('あなたの本棚をつくろう','book'):!data.books.some(b=>(filter==='all'||filter===b.status)&&(category==='all'||category===b.category)&&matches(b.title,b.author,b.review,b.genre||''))&&<p>該当する本がありません。</p>}</div>}
 {page==='settings'&&<div className="panel settings"><h2>データのバックアップ</h2><p>日課の履歴、メモ、本棚をまとめてJSONファイルに保存します。</p><button className="primary" onClick={backup}><Download size={17}/>データを書き出す</button><h2>バックアップから復元</h2><p>現在のデータ全体を置き換えます。先に書き出しておくことをおすすめします。</p><input aria-label="バックアップを選択" type="file" accept=".json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>2000000)throw Error('ファイルが大きすぎます。');const v=JSON.parse(await file.text());if(v.format!=='benrin-v1'||!validState(v.state))throw Error('benrinのバックアップではありません。');if(confirm('現在のデータをバックアップの内容に置き換えますか？'))update(()=>v.state);}catch(err){setError((err as Error).message);}e.target.value='';}}/><h2>表示</h2><button className="secondary" onClick={()=>setDark(!dark)}>{dark?'ライトモードにする':'ダークモードにする'}</button><h2>このスペースについて</h2><p>日本時間（午前0時更新）・週は月曜日から。日課の完了履歴は期間ごとに保存されます。指定日がない月は月末を期限とします。</p><p>メモは入力後に自動保存されます。「保存済み」を確認してから画面を閉じてください。</p></div>}
 </>}
 <footer>benrin <span>毎日を、少しだけ心地よく。</span><small>JAPAN STANDARD TIME</small></footer></div>}</main>
 {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&& (modal==='note'||confirm('編集を閉じますか？ 未保存の入力は破棄されます。')))setModal(null)}}><section className="modal" role="dialog" aria-modal="true" aria-label={modal==='routine'?'日課の編集':modal==='note'?'メモの編集':'本の編集'}><div className="section-head"><h2>{modal==='routine'?'続けたいこと':modal==='note'?'メモを書く':'本の記録'}</h2><button className="icon-button" aria-label="閉じる" onClick={()=>{if(modal==='note'||confirm('編集を閉じますか？ 未保存の入力は破棄されます。'))setModal(null)}}><X/></button></div><form onSubmit={e=>{e.preventDefault();if(modal==='routine')storeItem('routine',routine);if(modal==='note')storeItem('note',note);if(modal==='book')storeItem('book',book);setModal(null)}}>
 {modal==='routine'&&<><label>名前<input autoFocus required maxLength={200} value={routine.title} onChange={e=>setRoutine({...routine,title:e.target.value})} placeholder="例：20分、本を読む"/></label><label>繰り返し<select value={routine.frequency} onChange={e=>setRoutine({...routine,frequency:e.target.value as Routine['frequency']})}>{(['daily','weekly','monthly'] as const).map(v=><option value={v} key={v}>{labels[v]}</option>)}</select></label>{routine.frequency==='daily'&&<fieldset><legend>曜日（未選択なら毎日）</legend><div className="weekdays">{Array.from('日月火水木金土').map((d,i)=><button className={routine.weekdays.includes(i)?'primary':'secondary'} type="button" key={d} aria-pressed={routine.weekdays.includes(i)} onClick={()=>setRoutine({...routine,weekdays:routine.weekdays.includes(i)?routine.weekdays.filter(x=>x!==i):[...routine.weekdays,i]})}>{d}</button>)}</div></fieldset>}{routine.frequency==='weekly'&&<p className="help">月曜から日曜までの間に1回。翌週には新しいチェック欄になります。</p>}{routine.frequency==='monthly'&&<label>取り組む日<select value={routine.day} onChange={e=>setRoutine({...routine,day:Number(e.target.value)})}><option value={0}>月内に1回（いつでも）</option>{Array.from({length:31},(_,i)=><option key={i} value={i+1}>{i===30?'月末（31日）':`${i+1}日から月末まで`}</option>)}</select><small>指定日がない月は、その月の最終日に表示します。</small></label>}<label className="checkbox-label"><input type="checkbox" checked={routine.paused} onChange={e=>setRoutine({...routine,paused:e.target.checked})}/>一時停止する</label></>}
 {modal==='note'&&<><p className="help">入力内容は自動保存されます · {save}</p><label>タイトル<input autoFocus maxLength={200} value={note.title} onChange={e=>{const n={...note,title:e.target.value};setNote(n);storeItem('note',n)}} placeholder="無題のメモ"/></label><label>本文<textarea rows={10} maxLength={100000} value={note.body} onChange={e=>{const n={...note,body:e.target.value};setNote(n);storeItem('note',n)}} placeholder="いま、思っていることを。"/></label><label>タグ（カンマ区切り）<input maxLength={500} value={note.tags} onChange={e=>{const n={...note,tags:e.target.value};setNote(n);storeItem('note',n)}} placeholder="暮らし, アイデア"/></label><label>関連する本<select value={note.bookId} onChange={e=>{const n={...note,bookId:e.target.value};setNote(n);storeItem('note',n)}}><option value="">紐づけない</option>{data.books.map(b=><option value={b.id} key={b.id}>{b.title}</option>)}</select></label></>}
 {modal==='book'&&<><label>書名<input autoFocus required maxLength={200} value={book.title} onChange={e=>setBook({...book,title:e.target.value})}/></label><label>著者<input maxLength={200} value={book.author} onChange={e=>setBook({...book,author:e.target.value})}/></label><div className="form-columns"><label>読書状態<select value={book.status} onChange={e=>setBook({...book,status:e.target.value as Book['status'],finished:e.target.value==='read'?(book.finished||date):''})}>{(['unknown','unread','reading','read'] as const).map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label><label>評価<select value={book.rating} onChange={e=>setBook({...book,rating:Number(e.target.value)})}><option value={0}>未評価</option>{[1,2,3,4,5].map(v=><option key={v} value={v}>{'★'.repeat(v)}</option>)}</select></label></div>{book.status==='read'&&<label>読了日<input type="date" value={book.finished} onChange={e=>setBook({...book,finished:e.target.value})}/></label>}<div className="form-columns"><label>種類<select value={book.category||''} onChange={e=>setBook({...book,category:e.target.value})}><option value="">その他</option><option value="漫画">漫画</option><option value="小説">小説</option></select></label><label>ジャンル<input maxLength={200} value={book.genre||''} onChange={e=>setBook({...book,genre:e.target.value})}/></label></div>{book.category==='漫画'&&<div className="form-columns"><label>既読巻数<input type="number" min="0" value={book.readVolumes||''} onChange={e=>setBook({...book,readVolumes:e.target.value})}/></label><label>総巻数<input type="number" min="0" value={book.totalVolumes||''} onChange={e=>setBook({...book,totalVolumes:e.target.value})}/></label></div>}<label>媒体<input maxLength={200} value={book.medium||''} onChange={e=>setBook({...book,medium:e.target.value})}/></label><label>概要<textarea rows={3} maxLength={100000} value={book.summary||''} onChange={e=>setBook({...book,summary:e.target.value})}/></label>{book.sourceSheet&&<p className="help">取り込み元：{book.sourceSheet} / 行 {book.sourceRows?.join(', ')}{book.sourceStatus&&' / 元の状態：'+book.sourceStatus}{book.sourceUpdated&&' / 更新日：'+book.sourceUpdated}</p>}<label>感想・心に残った言葉<textarea rows={5} maxLength={100000} value={book.review} onChange={e=>setBook({...book,review:e.target.value})}/></label>{data.notes.filter(n=>n.bookId===book.id).length>0&&<div><h3>関連するメモ</h3>{data.notes.filter(n=>n.bookId===book.id).map(n=><p key={n.id}>{n.title||'無題のメモ'}</p>)}</div>}</>}
 <div className="modal-actions">{(editing||modal==='note'&&data.notes.some(n=>n.id===note.id))&&<button type="button" className="danger" onClick={()=>remove(modal,modal==='routine'?routine.id:modal==='note'?note.id:book.id)}><Trash2 size={16}/>削除</button>}<button className="primary" type="submit">{modal==='note'?'保存して閉じる':'保存する'}</button></div></form></section></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
